# Generated by Django 3.0.4 on 2020-03-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200323_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
